# Generated by Django 3.2.5 on 2021-07-27 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('sku', models.CharField(max_length=10, unique=True)),
                ('imagen', models.TextField(max_length=3000)),
                ('tags', models.CharField(max_length=100)),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Activo'), (0, 'Archivado'), (2, 'Borrador')], null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('talla', models.CharField(max_length=100)),
                ('fecha', models.DateField(blank=True)),
                ('fecha_actualizada', models.DateField(blank=True)),
            ],
        ),
    ]
