# Generated by Django 3.2.5 on 2021-07-27 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
